### ISSUE TITLE
Docker Environment-Variable TZ not working

### ISSUE THREAD

**Issue by SHU-red** [EasyPi/docker-urlwatch#5]
Using

```
    environment:
      - EDITOR=/usr/bin/vi
      - TZ=Europe/Berlin
```

returns

```
tzlocal() does not support non-zoneinfo timezones like Europe/Berlin. \nPlease use a timezone in the form of Continent/City
```

I tested many variants and googled but could not find a solution

**Comment by vimagick** [comment]
I've installed a new package (`tzdata`), please pull the latest image, and try again.

https://github.com/EasyPi/docker-urlwatch/blob/master/Dockerfile#L24

**Comment by SHU-red** [comment]
Works just perfect!

Thank you very much!
